image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    live:

      # BACKUP poprzedniej wersji
      - step:
          name: Backup live → preview
          script:
            - git config --global user.email "pipeline@bitbucket"
            - git config --global user.name "Bitbucket Pipeline"
            - git fetch --unshallow || true
            - git fetch --all
            - git push origin origin/live~1:preview --force

      # BUILD BACKEND
      - step:
          name: Build Backend
          size: 2x
          caches:
            - dotnetcore
          script:
            - set -e
            - apt-get update && apt-get install -y zip

            - cd DigitalWars.Server
            - dotnet restore
            - dotnet publish -c Release -o ../deployment-backend
            - cd ..

            - cd deployment-backend
            - zip -r ../app-backend.zip .
            - cd ..
          artifacts:
            - app-backend.zip

      # BUILD FRONTEND
      - step:
          name: Build Frontend
          caches:
            - node
          script:
            - set -e
            - apt-get update && apt-get install -y zip
            - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            - apt-get install -y nodejs

            - cd digitalwars.client

            # Build frontendu
            - export VITE_API_URL="$VITE_API_URL"
            - npm ci
            - npm run build

            - test -d dist

            # Pakowanie frontendu
            - cd dist
            - zip -r ../../app-frontend.zip .
            - cd ../..
          artifacts:
            - app-frontend.zip

      # DEPLOY BACKEND + FRONTEND
      - step:
          name: Deploy backend & frontend
          image: mcr.microsoft.com/azure-cli
          deployment: production
          script:
            - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID

            # BACKEND DEPLOY
            - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_BACKEND --src app-backend.zip


            # FRONTEND DEPLOY
            - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_FRONTEND --src app-frontend.zip