image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    live:
      - step:
          name: Backup live → preview
          script:
            - git fetch --all
            - git push origin origin/live~1:preview --force

      - parallel:
          # --- PROCES BACKEND ---
          - step:
              name: Build & Deploy Backend
              size: 2x
              caches:
                - dotnetcore
              script:
                - dotnet publish DigitalWars.Server/DigitalWars.Server.csproj -c Release -o ./publish-backend
                # Pakujemy zawartość folderu do pliku w głównym katalogu (używamy pwsh zamiast apt install zip)
                - pwsh -Command "Compress-Archive -Path ./publish-backend/* -DestinationPath ./app-backend.zip"
                - pipe: microsoft/azure-web-apps-deploy:1.0.3
                  variables:
                    AZURE_APP_ID: $AZURE_APP_ID
                    AZURE_PASSWORD: $AZURE_PASSWORD
                    AZURE_TENANT_ID: $AZURE_TENANT_ID
                    AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                    AZURE_APP_NAME: $AZURE_WEBAPP_BACKEND
                    ZIP_FILE: "app-backend.zip"

          # --- PROCES FRONTEND ---
          - step:
              name: Build & Deploy Frontend
              image: node:20
              caches:
                - node
              script:
                # 1. Instalacja zip (Node jest już w obrazie)
                - apt-get update && apt-get install -y zip
                # 2. Build
                - cd digitalwars.client
                - npm ci
                - npm run build
                # 3. Pakowanie (wchodzimy do dist, żeby w ZIPie nie było folderu "dist", tylko sama treść)
                - cd dist && zip -r ../../app-frontend.zip . && cd ../..
                # 4. Deploy (teraz jesteśmy w root, gdzie jest app-frontend.zip)
                - pipe: microsoft/azure-web-apps-deploy:1.0.3
                  variables:
                    AZURE_APP_ID: $AZURE_APP_ID
                    AZURE_PASSWORD: $AZURE_PASSWORD
                    AZURE_TENANT_ID: $AZURE_TENANT_ID
                    AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                    AZURE_APP_NAME: $AZURE_WEBAPP_FRONTEND
                    ZIP_FILE: "app-frontend.zip"