// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace DigitalWars.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.Property<int>("Boards_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Boards_Id"));

                    b.Property<string>("Border_Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Borders_Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell_Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("Cols")
                        .HasColumnType("int");

                    b.Property<string>("Description_Down")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description_Left")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Labels_Right")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels_Up")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<int?>("Users_Id")
                        .HasColumnType("int");

                    b.HasKey("Boards_Id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("backend.Data.Card", b =>
                {
                    b.Property<int>("Cards_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cards_Id"));

                    b.Property<int>("Card_Id")
                        .HasColumnType("int");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Modules_Id")
                        .HasColumnType("int");

                    b.HasKey("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.HasIndex("Modules_Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("backend.Data.CardEnabler", b =>
                {
                    b.Property<int>("Cards_Enablers_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cards_Enablers_Id"));

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Enablers_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Games_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Teams_Id")
                        .HasColumnType("int");

                    b.HasKey("Cards_Enablers_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Enablers_Id");

                    b.HasIndex("Games_Id");

                    b.HasIndex("Teams_Id");

                    b.ToTable("CardEnablers");
                });

            modelBuilder.Entity("backend.Data.CardWeight", b =>
                {
                    b.Property<int>("Cards_Weights_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cards_Weights_Id"));

                    b.Property<double>("Booster_X")
                        .HasColumnType("double");

                    b.Property<double>("Booster_Y")
                        .HasColumnType("double");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<int>("Processes_Id")
                        .HasColumnType("int");

                    b.Property<int>("Weights_X")
                        .HasColumnType("int");

                    b.Property<int>("Weights_Y")
                        .HasColumnType("int");

                    b.HasKey("Cards_Weights_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Processes_Id");

                    b.ToTable("CardWeights");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.Property<int>("Decisions_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Decisions_Id"));

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<double>("Decisions_Cost_Bits")
                        .HasColumnType("double");

                    b.Property<double>("Decisions_Cost_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Cost_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Cost_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Decisions_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Decisions_Reward_Bits")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Reward_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Reward_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Reward_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Decisions_Short_Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Decisions_Id");

                    b.HasIndex("Cards_Id");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.Property<int>("Decks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Decks_Id"));

                    b.Property<string>("Deck_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Users_Id")
                        .HasColumnType("int");

                    b.HasKey("Decks_Id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.Property<int>("Feedbacks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Feedbacks_Id"));

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<string>("Feedbacks_Long_Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Feedbacks_PDF")
                        .HasColumnType("LONGBLOB");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Feedbacks_Id");

                    b.HasIndex("Cards_Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Property<int>("Games_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Id"));

                    b.Property<int>("Decks_Id")
                        .HasColumnType("int");

                    b.Property<string>("Game_Status")
                        .HasColumnType("ENUM('During', 'Paused', 'End')");

                    b.Property<string>("Games_Desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Is_Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Modules_Id")
                        .HasColumnType("int");

                    b.Property<int>("Rivals_Boards_Id")
                        .HasColumnType("int");

                    b.Property<int>("Teams_Boards_Id")
                        .HasColumnType("int");

                    b.Property<int>("Users_Id")
                        .HasColumnType("int");

                    b.HasKey("Games_Id");

                    b.HasIndex("Decks_Id");

                    b.HasIndex("Modules_Id");

                    b.HasIndex("Rivals_Boards_Id");

                    b.HasIndex("Teams_Boards_Id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.Property<int>("Games_Boards_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Boards_Id"));

                    b.Property<int>("Boards_Id")
                        .HasColumnType("int");

                    b.Property<int>("Games_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Games_Processes_Id")
                        .HasColumnType("int");

                    b.Property<double>("Poz_X")
                        .HasColumnType("double");

                    b.Property<double>("Poz_Y")
                        .HasColumnType("double");

                    b.Property<int>("Teams_Id")
                        .HasColumnType("int");

                    b.HasKey("Games_Boards_Id");

                    b.HasIndex("Boards_Id");

                    b.HasIndex("Games_Id");

                    b.HasIndex("Games_Processes_Id");

                    b.HasIndex("Teams_Id");

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.Property<int>("Games_Events_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Events_Id"));

                    b.Property<double?>("Boosters_X")
                        .HasColumnType("double");

                    b.Property<double?>("Boosters_Y")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Costs_Bits_Weights")
                        .HasColumnType("double");

                    b.Property<double?>("Decisions_Costs_PD_Weights")
                        .HasColumnType("double");

                    b.Property<int?>("Decks_Id")
                        .HasColumnType("int");

                    b.Property<string>("Events_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Events_Short_Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Hardwares_Costs_Bits_Weights")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Costs_PD_Weights")
                        .HasColumnType("double");

                    b.Property<int?>("Modules_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Softwares_Costs_Bits_Weights")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Costs_PD_Weights")
                        .HasColumnType("double");

                    b.Property<int>("Turns_Time")
                        .HasColumnType("int");

                    b.HasKey("Games_Events_Id");

                    b.HasIndex("Decks_Id");

                    b.HasIndex("Modules_Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Property<int>("Games_Logs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Logs_Id"));

                    b.Property<int?>("Boards_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Booster_X")
                        .HasColumnType("double");

                    b.Property<double?>("Booster_Y")
                        .HasColumnType("double");

                    b.Property<int?>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Costs")
                        .HasColumnType("double");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Feedbacks_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Games_Events_Id")
                        .HasColumnType("int");

                    b.Property<int>("Games_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Is_Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Teams_Id")
                        .HasColumnType("int");

                    b.HasKey("Games_Logs_Id");

                    b.HasIndex("Boards_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Feedbacks_Id");

                    b.HasIndex("Games_Events_Id");

                    b.HasIndex("Games_Id");

                    b.HasIndex("Teams_Id");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.Property<int>("Games_Logs_Specs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Logs_Specs_Id"));

                    b.Property<int>("Games_Logs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Games_Processes_Id")
                        .HasColumnType("int");

                    b.Property<int>("Moves_X")
                        .HasColumnType("int");

                    b.Property<int>("Moves_Y")
                        .HasColumnType("int");

                    b.HasKey("Games_Logs_Specs_Id");

                    b.HasIndex("Games_Logs_Id");

                    b.HasIndex("Games_Processes_Id");

                    b.ToTable("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.Property<int>("Games_Processes_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Games_Processes_Id"));

                    b.Property<int>("Games_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Games_Processes_Weights")
                        .HasColumnType("int");

                    b.Property<int>("Processes_Id")
                        .HasColumnType("int");

                    b.Property<int>("Teams_Id")
                        .HasColumnType("int");

                    b.HasKey("Games_Processes_Id");

                    b.HasIndex("Games_Id");

                    b.HasIndex("Processes_Id");

                    b.HasIndex("Teams_Id");

                    b.ToTable("GameProcesses");
                });

            modelBuilder.Entity("backend.Data.Hardware", b =>
                {
                    b.Property<int>("Hardwares_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Hardwares_Id"));

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<double>("Hardwares_Cost_Bits")
                        .HasColumnType("double");

                    b.Property<double>("Hardwares_Cost_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Cost_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Cost_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Hardwares_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Hardwares_Reward_Bits")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Reward_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Reward_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Hardwares_Reward_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Hardwares_Short_Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Hardwares_Id");

                    b.HasIndex("Cards_Id");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("backend.Data.Module", b =>
                {
                    b.Property<int>("Modules_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Modules_Id"));

                    b.Property<int>("Decks_Id")
                        .HasColumnType("int");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Modules_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("backend.Data.Process", b =>
                {
                    b.Property<int>("Processes_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Processes_Id"));

                    b.Property<int>("Decks_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Modules_Id")
                        .HasColumnType("int");

                    b.Property<string>("Processes_Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Processes_Desc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Processes_Long_Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Processes_Weight")
                        .HasColumnType("double");

                    b.HasKey("Processes_Id");

                    b.HasIndex("Decks_Id");

                    b.HasIndex("Modules_Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("backend.Data.Software", b =>
                {
                    b.Property<int>("Softwares_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Softwares_Id"));

                    b.Property<int>("Cards_Id")
                        .HasColumnType("int");

                    b.Property<double>("Softwares_Cost_Bits")
                        .HasColumnType("double");

                    b.Property<double>("Softwares_Cost_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Cost_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Cost_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Softwares_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Softwares_Reward_Bits")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Reward_Bits_Weight")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Reward_PD")
                        .HasColumnType("double");

                    b.Property<double?>("Softwares_Reward_PD_Weight")
                        .HasColumnType("double");

                    b.Property<string>("Softwares_Short_Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Softwares_Id");

                    b.HasIndex("Cards_Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Property<int>("Teams_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Teams_Id"));

                    b.Property<int?>("Games_Events_Id")
                        .HasColumnType("int");

                    b.Property<int>("Games_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Independent")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Teams_Bud")
                        .HasColumnType("double");

                    b.Property<string>("Teams_Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Teams_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Teams_PD")
                        .HasColumnType("double");

                    b.Property<string>("Teams_Token")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int?>("Turns_Left")
                        .HasColumnType("int");

                    b.HasKey("Teams_Id");

                    b.HasIndex("Games_Events_Id");

                    b.HasIndex("Games_Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Data.User", b =>
                {
                    b.Property<int>("Users_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Users_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Email_Confirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Games_In_Progress")
                        .HasColumnType("int");

                    b.Property<int>("Licenses_Owned")
                        .HasColumnType("int");

                    b.Property<int>("Licenses_Used")
                        .HasColumnType("int");

                    b.Property<string>("Link_Token")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Token_Expire_Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Users_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("Users_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Card", b =>
                {
                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Modules_Id");

                    b.Navigation("Deck");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("backend.Data.CardEnabler", b =>
                {
                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany("DecisionEnablers")
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Card", "Enablers")
                        .WithMany("DecisionEnablerOfThis")
                        .HasForeignKey("Enablers_Id");

                    b.HasOne("backend.Data.Game", "Games")
                        .WithMany()
                        .HasForeignKey("Games_Id");

                    b.HasOne("backend.Data.Team", "Teams")
                        .WithMany()
                        .HasForeignKey("Teams_Id");

                    b.Navigation("Cards");

                    b.Navigation("Enablers");

                    b.Navigation("Games");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.CardWeight", b =>
                {
                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Process", "Processes")
                        .WithMany()
                        .HasForeignKey("Processes_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("Users_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.HasOne("backend.Data.Deck", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Module", "Modules")
                        .WithMany()
                        .HasForeignKey("Modules_Id");

                    b.HasOne("backend.Data.Board", "Rivals_Boards")
                        .WithMany("RivalGames")
                        .HasForeignKey("Rivals_Boards_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Board", "Teams_Boards")
                        .WithMany("TeamGames")
                        .HasForeignKey("Teams_Boards_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.User", "Users")
                        .WithMany()
                        .HasForeignKey("Users_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decks");

                    b.Navigation("Modules");

                    b.Navigation("Rivals_Boards");

                    b.Navigation("Teams_Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.HasOne("backend.Data.Board", "Boards")
                        .WithMany()
                        .HasForeignKey("Boards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Game", "Games")
                        .WithMany("GameBoards")
                        .HasForeignKey("Games_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.GameProcess", "Games_Processes")
                        .WithMany()
                        .HasForeignKey("Games_Processes_Id");

                    b.HasOne("backend.Data.Team", "Teams")
                        .WithMany()
                        .HasForeignKey("Teams_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boards");

                    b.Navigation("Games");

                    b.Navigation("Games_Processes");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.HasOne("backend.Data.Deck", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id");

                    b.HasOne("backend.Data.Module", "Modules")
                        .WithMany()
                        .HasForeignKey("Modules_Id");

                    b.Navigation("Decks");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.HasOne("backend.Data.Board", "Boards")
                        .WithMany()
                        .HasForeignKey("Boards_Id");

                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id");

                    b.HasOne("backend.Data.Feedback", "Feedbacks")
                        .WithMany()
                        .HasForeignKey("Feedbacks_Id");

                    b.HasOne("backend.Data.GameEvent", "Games_Events")
                        .WithMany("GameLogs")
                        .HasForeignKey("Games_Events_Id");

                    b.HasOne("backend.Data.Game", "Games")
                        .WithMany("GameLogs")
                        .HasForeignKey("Games_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Team", "Teams")
                        .WithMany()
                        .HasForeignKey("Teams_Id");

                    b.Navigation("Boards");

                    b.Navigation("Cards");

                    b.Navigation("Feedbacks");

                    b.Navigation("Games");

                    b.Navigation("Games_Events");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.HasOne("backend.Data.GameLog", "Games_Logs")
                        .WithMany("GameLogSpecs")
                        .HasForeignKey("Games_Logs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.GameProcess", "Games_Processes")
                        .WithMany()
                        .HasForeignKey("Games_Processes_Id");

                    b.Navigation("Games_Logs");

                    b.Navigation("Games_Processes");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.HasOne("backend.Data.Game", "Games")
                        .WithMany("GameProcesses")
                        .HasForeignKey("Games_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Process", "Processes")
                        .WithMany()
                        .HasForeignKey("Processes_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Team", "Teams")
                        .WithMany("Game_Processes")
                        .HasForeignKey("Teams_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");

                    b.Navigation("Processes");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.Hardware", b =>
                {
                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("backend.Data.Module", b =>
                {
                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("backend.Data.Process", b =>
                {
                    b.HasOne("backend.Data.Deck", "Decks")
                        .WithMany("Processes")
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Module", "Modules")
                        .WithMany()
                        .HasForeignKey("Modules_Id");

                    b.Navigation("Decks");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("backend.Data.Software", b =>
                {
                    b.HasOne("backend.Data.Card", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.HasOne("backend.Data.GameEvent", "Games_Events")
                        .WithMany("Teams")
                        .HasForeignKey("Games_Events_Id");

                    b.HasOne("backend.Data.Game", "Games")
                        .WithMany("Teams")
                        .HasForeignKey("Games_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");

                    b.Navigation("Games_Events");
                });

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.Navigation("RivalGames");

                    b.Navigation("TeamGames");
                });

            modelBuilder.Entity("backend.Data.Card", b =>
                {
                    b.Navigation("DecisionEnablerOfThis");

                    b.Navigation("DecisionEnablers");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Navigation("GameBoards");

                    b.Navigation("GameLogs");

                    b.Navigation("GameProcesses");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.Navigation("GameLogs");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Navigation("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Navigation("Game_Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
