// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace DigitalWars.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("BorderColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CellColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("Cols")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionDown")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DescriptionLeft")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LabelsRight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsUp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("backend.Data.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("ENUM('Decision', 'Item')");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<double>("DecisionBaseCost")
                        .HasColumnType("double");

                    b.Property<double>("DecisionCostWeight")
                        .HasColumnType("double");

                    b.Property<string>("DecisionLongDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionShortDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.HasKey("DecisionId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("backend.Data.DecisionEnabler", b =>
                {
                    b.Property<int>("DecisionEnablerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionEnablerId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int?>("EnablerId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("DecisionEnablerId");

                    b.HasIndex("CardId");

                    b.HasIndex("EnablerId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("DecisionEnablers");
                });

            modelBuilder.Entity("backend.Data.DecisionWeight", b =>
                {
                    b.Property<int>("DecisionWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionWeightId"));

                    b.Property<double>("BoosterX")
                        .HasColumnType("double");

                    b.Property<double>("BoosterY")
                        .HasColumnType("double");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("WeightX")
                        .HasColumnType("int");

                    b.Property<int>("WeightY")
                        .HasColumnType("int");

                    b.HasKey("DecisionWeightId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.HasIndex("ProcessId");

                    b.ToTable("DecisionWeights");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FeedbackPDF")
                        .HasColumnType("LONGBLOB");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("GameDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GameStatus")
                        .HasColumnType("ENUM('During', 'Paused', 'End')");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RivalBoardId")
                        .HasColumnType("int");

                    b.Property<int>("TeamBoardId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("DeckId");

                    b.HasIndex("RivalBoardId");

                    b.HasIndex("TeamBoardId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.Property<int>("GameBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameBoardId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GameProcessId")
                        .HasColumnType("int");

                    b.Property<double>("PozX")
                        .HasColumnType("double");

                    b.Property<double>("PozY")
                        .HasColumnType("double");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameBoardId");

                    b.HasIndex("BoardId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameProcessId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.Property<int>("GameEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameEventId"));

                    b.Property<double?>("BoosterX")
                        .HasColumnType("double");

                    b.Property<double?>("BoosterY")
                        .HasColumnType("double");

                    b.Property<double?>("DecisionCostWeight")
                        .HasColumnType("double");

                    b.Property<string>("EventLongDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventShortDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("ItemsCostWeight")
                        .HasColumnType("double");

                    b.Property<int>("TurnTime")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameEventId");

                    b.HasIndex("UserId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Property<int>("GameLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameLogId"));

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<double?>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int?>("GameEventId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameLogId");

                    b.HasIndex("BoardId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("GameEventId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.Property<int>("GameLogSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameLogSpecId"));

                    b.Property<int>("GameLogId")
                        .HasColumnType("int");

                    b.Property<int?>("GameProcessId")
                        .HasColumnType("int");

                    b.Property<int>("MoveX")
                        .HasColumnType("int");

                    b.Property<int>("MoveY")
                        .HasColumnType("int");

                    b.HasKey("GameLogSpecId");

                    b.HasIndex("GameLogId");

                    b.HasIndex("GameProcessId");

                    b.ToTable("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.Property<int>("GameProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameProcessId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameProcessId");

                    b.HasIndex("GameId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameProcesses");
                });

            modelBuilder.Entity("backend.Data.Item", b =>
                {
                    b.Property<int>("ItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemsId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("HardwareLongDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareShortDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ItemsBaseCost")
                        .HasColumnType("double");

                    b.Property<double>("ItemsCostWeight")
                        .HasColumnType("double");

                    b.HasKey("ItemsId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("backend.Data.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ProcessDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ProcessLongDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ProcessWeight")
                        .HasColumnType("double");

                    b.HasKey("ProcessId");

                    b.HasIndex("DeckId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("GameEventId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIndependent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TeamBud")
                        .HasColumnType("int");

                    b.Property<string>("TeamColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeamToken")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int?>("TurnsLeft")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("GameEventId");

                    b.HasIndex("GameId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LicensesOwned")
                        .HasColumnType("int");

                    b.Property<int>("LicensesUsed")
                        .HasColumnType("int");

                    b.Property<string>("LinkToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenExpireDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany("Decisions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("backend.Data.DecisionEnabler", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany("DecisionEnablers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Card", "CardEnabler")
                        .WithMany("DecisionEnablerOfThis")
                        .HasForeignKey("EnablerId");

                    b.HasOne("backend.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("backend.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Card");

                    b.Navigation("CardEnabler");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Data.DecisionWeight", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany("Feedbacks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Board", "RivalBoard")
                        .WithMany()
                        .HasForeignKey("RivalBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Board", "TeamBoard")
                        .WithMany()
                        .HasForeignKey("TeamBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("RivalBoard");

                    b.Navigation("TeamBoard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.HasOne("backend.Data.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Game", "Game")
                        .WithMany("GameBoards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.GameProcess", "GameProcess")
                        .WithMany()
                        .HasForeignKey("GameProcessId");

                    b.HasOne("backend.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Game");

                    b.Navigation("GameProcess");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.HasOne("backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.HasOne("backend.Data.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId");

                    b.HasOne("backend.Data.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId");

                    b.HasOne("backend.Data.GameEvent", "GameEvent")
                        .WithMany("GameLogs")
                        .HasForeignKey("GameEventId");

                    b.HasOne("backend.Data.Game", "Game")
                        .WithMany("GameLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Board");

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("Feedback");

                    b.Navigation("Game");

                    b.Navigation("GameEvent");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.HasOne("backend.Data.GameLog", "GameLog")
                        .WithMany("GameLogSpecs")
                        .HasForeignKey("GameLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.GameProcess", "GameProcess")
                        .WithMany()
                        .HasForeignKey("GameProcessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameLog");

                    b.Navigation("GameProcess");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.HasOne("backend.Data.Game", "Game")
                        .WithMany("GameProcesses")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Team", "Team")
                        .WithMany("GameProcesses")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Process");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Data.Item", b =>
                {
                    b.HasOne("backend.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany("Items")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("backend.Data.Process", b =>
                {
                    b.HasOne("backend.Data.Deck", "Deck")
                        .WithMany("Processes")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.HasOne("backend.Data.GameEvent", "GameEvent")
                        .WithMany("Teams")
                        .HasForeignKey("GameEventId");

                    b.HasOne("backend.Data.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameEvent");
                });

            modelBuilder.Entity("backend.Data.Card", b =>
                {
                    b.Navigation("DecisionEnablerOfThis");

                    b.Navigation("DecisionEnablers");
                });

            modelBuilder.Entity("backend.Data.Deck", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Feedbacks");

                    b.Navigation("Items");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Navigation("GameBoards");

                    b.Navigation("GameLogs");

                    b.Navigation("GameProcesses");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameEvent", b =>
                {
                    b.Navigation("GameLogs");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Navigation("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Navigation("GameProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
